### ISSUE TITLE
Unable to convert JSON to PNG

### ISSUE THREAD

**Issue by Apoorvneema** [mapbox/webgl-wind#6]
when  i run download.sh following error came please help

>./download.sh 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 75719    0 75719    0     0  40493      0 --:--:--  0:00:01 --:--:-- 40491
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 76321    0 76321    0     0  43553      0 --:--:--  0:00:01 --:--:-- 43537
GRIB_API ERROR   :  unable to get groupSplittingMethodUsed as long (Key/value not found)
GRIB_API ERROR   :  unable to get codedValues as double array (Key/value not found)
GRIB_API ERROR   :  unable to get values as double array (Key/value not found)
GRIB_API ERROR   :  unable to get groupSplittingMethodUsed as long (Key/value not found)
GRIB_API ERROR   :  unable to get codedValues as double array (Key/value not found)
GRIB_API ERROR   :  unable to get values as double array (Key/value not found)
module.js:328
    throw err;
    ^

Error: Cannot find module 'pngjs'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/user/Computer Graphics/newWEBGL/webgl-wind/data/prepare.js:1:75)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)

**Comment by mourner** [comment]
Oh, you first need to do `npm install` in the root repo directory (provided you have Node.js installed). I should probably make that clearer in the readme. Thanks!
